/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xAB, 0x22, 0x68, 0x8B, 0x59, 0xD0, 0x81, 0x11}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define ENCODER_RESOLUTION 2
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define DYNAMIC_KEYMAP_MACRO_COUNT 64
#define HOLD_ON_OTHER_KEY_PRESS
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define MIDI_ADVANCED


#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_OLED_ENABLE

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE 	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE 	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE 	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE 	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS 	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS 	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS 	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS 	
#define ENABLE_RGB_MATRIX_SPLASH 	
#define ENABLE_RGB_MATRIX_MULTISPLASH 	
#define ENABLE_RGB_MATRIX_SOLID_SPLASH 	
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH