
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CAPS_WORD_ENABLE = yes
VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
MIDI_ENABLE = yes
TRI_LAYER_ENABLE = yes
